import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=id=>document.getElementById(id),canvas=$('game'),loading=$('loading'),fatal=$('fatal'),loadText=$('loadText'),loadFill=$('loadFill');
const hasWebGL=(()=>{try{const c=document.createElement('canvas');return !!(c.getContext('webgl2')||c.getContext('webgl'))}catch{return false}})();
if(!hasWebGL){loading.remove();fatal.hidden=false;fatal.innerHTML='<div><b>WebGL недоступен</b><br>Открой страницу в обычном Safari и отключи режим энергосбережения.</div>';throw new Error('WebGL unavailable')}
let renderer;try{renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance',alpha:false})}catch(e){loading.remove();fatal.hidden=false;fatal.textContent='Не удалось создать 3D-сцену: '+e.message;throw e}
const weak=(navigator.hardwareConcurrency||4)<=4||innerWidth<390;let quality=weak?'economy':'high';function applyQuality(){const high=quality==='high';renderer.setPixelRatio(Math.min(devicePixelRatio||1,high?1.45:1));renderer.shadowMap.enabled=true;renderer.shadowMap.type=high?THREE.PCFSoftShadowMap:THREE.PCFShadowMap;$('quality').textContent='КАЧЕСТВО: '+(high?'ВЫСОКОЕ':'ЭКОНОМ')}applyQuality();renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x96c5d7);scene.fog=new THREE.FogExp2(0x9ebeca,.015);const camera=new THREE.PerspectiveCamera(46,innerWidth/innerHeight,.1,200);camera.position.set(11,10,14);
scene.add(new THREE.HemisphereLight(0xe8f7ff,0x44352a,1.7));const sun=new THREE.DirectionalLight(0xffddb0,4.2);sun.position.set(-18,24,-12);sun.castShadow=true;sun.shadow.mapSize.set(weak?1024:2048,weak?1024:2048);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;sun.shadow.bias=-.0005;scene.add(sun);
const M=(c,r=.85,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});const mats={grass:M(0x4d6e3d,1),dirt:M(0x79513a,1),concrete:M(0xa5a6a1,.94),brick:M(0xa44728,.9),brick2:M(0xc05f35,.9),wood:M(0x8c5b30,.9),dark:M(0x20272c,.75,.1),orange:M(0xe58a0b,.62,.05),glass:M(0x2d7893,.2,.1),steel:M(0x60686d,.5,.55),white:M(0xe7e4dc,.78)};const world=new THREE.Group();scene.add(world);
function mesh(g,m,x,y,z,cast=true){const o=new THREE.Mesh(g,m);o.position.set(x,y,z);o.castShadow=cast;o.receiveShadow=true;world.add(o);return o}function box(x,y,z,w,h,d,m,cast=true){return mesh(new THREE.BoxGeometry(w,h,d),m,x,y,z,cast)}function cyl(x,y,z,r,h,m,seg=18){return mesh(new THREE.CylinderGeometry(r,r,h,seg),m,x,y,z)}
const ground=mesh(new THREE.PlaneGeometry(100,100),mats.grass,0,0,0,false);ground.rotation.x=-Math.PI/2;const site=mesh(new THREE.PlaneGeometry(38,30),mats.dirt,0,.012,0,false);site.rotation.x=-Math.PI/2;
for(let i=-20;i<=20;i+=3)box(i,.06,15,2.45,.12,3,mats.dark,false);for(let i=-18;i<=18;i+=2){box(i,1.15,-14.2,1.8,2.3,.08,mats.steel,false);box(i,.55,-14.15,.06,1.1,.06,mats.steel,false)}
for(let p=0;p<6;p++){const px=-12+(p%3)*2.6,pz=-6+Math.floor(p/3)*2.8;box(px,.12,pz,1.9,.22,1.3,mats.wood);for(let i=0;i<18;i++)box(px+(i%6)*.26-.65,.36+Math.floor(i/6)*.22,pz,.22,.18,.42,[mats.brick,mats.concrete,mats.wood,mats.dark,mats.brick2,mats.concrete][p])}
box(-13,1.55,4.8,5,3.1,3.6,M(0x274f40,.78));box(-13,3.17,4.8,5.25,.18,3.9,mats.dark);
// crane
const crane=new THREE.Group();world.add(crane);crane.position.set(11,0,-7);for(let y=.4;y<10;y+=.8){const a=box(11,y,-7,.18,.75,.18,mats.orange),b=box(12,y,-7,.18,.75,.18,mats.orange);a.rotation.z=.38;b.rotation.z=-.38}box(11.5,10,-7,9,.22,.22,mats.orange);box(15.8,8.5,-7,.08,3,.08,mats.steel);box(15.8,7,-7,.8,.55,.8,mats.concrete);
// excavator
const ex=new THREE.Group();world.add(ex);ex.position.set(10,0,7);const part=(g,geo,mat,x,y,z)=>{const o=new THREE.Mesh(geo,mat);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;g.add(o);return o};part(ex,new THREE.BoxGeometry(3.5,.55,2),mats.dark,0,.45,0);part(ex,new THREE.BoxGeometry(1.5,1.5,1.7),mats.orange,-.8,1.35,0);const boom=part(ex,new THREE.BoxGeometry(.35,.35,3.8),mats.orange,1.1,2.3,0);boom.rotation.z=-.6;const bucket=part(ex,new THREE.BoxGeometry(1,.7,1.5),mats.dark,2.75,1.05,0);for(const z of[-1.05,1.05])part(ex,new THREE.CylinderGeometry(.48,.48,.35,22),mats.dark,-.7,.45,z).rotation.x=Math.PI/2;
// build stages grow from ground
const build=[];function staged(o,a,b){o.visible=false;o.userData={a,b,baseY:o.position.y,height:o.geometry.parameters?.height||1};build.push(o);return o}function grow(o,q){o.visible=q>0;o.scale.y=Math.max(.02,q);o.position.y=o.userData.baseY-o.userData.height*(1-q)/2}
staged(box(2,-.18,0,9,.35,7,M(0x5a3d2c,1),false),0,.05);for(let x=-1.5;x<=5.5;x+=1){staged(box(x,.35,-3,.82,.7,.55,mats.concrete),.05,.14);staged(box(x,.35,3,.82,.7,.55,mats.concrete),.05,.14)}for(let z=-2;z<=2;z+=1){staged(box(-2,.35,z,.55,.7,.82,mats.concrete),.05,.14);staged(box(6,.35,z,.55,.7,.82,mats.concrete),.05,.14)}staged(box(2,.82,0,7.5,.35,5.5,mats.concrete),.14,.23);for(let r=0;r<8;r++)for(let x=-1.6;x<=5.6;x+=.72){staged(box(x,1.12+r*.34,-2.75,.62,.3,.34,r%2?mats.brick:mats.brick2),.23,.44);staged(box(x,1.12+r*.34,2.75,.62,.3,.34,r%2?mats.brick:mats.brick2),.23,.44)}staged(box(2,3.85,0,7.5,.3,5.5,mats.concrete),.44,.52);for(let r=0;r<7;r++)for(let x=-1.6;x<=5.6;x+=.72)staged(box(x,4.15+r*.34,-2.75,.62,.3,.34,mats.brick2),.52,.69);for(let i=0;i<14;i++){const x=-1.6+i*.55,a=staged(box(x,6.75,-.9,.12,.14,4.3,mats.wood),.69,.81),b=staged(box(x,6.75,.9,.12,.14,4.3,mats.wood),.69,.81);a.rotation.x=.55;b.rotation.x=-.55}for(let i=0;i<14;i++){const x=-1.6+i*.55,a=staged(box(x,7.02,-.98,.5,.12,4.45,mats.dark),.81,.95),b=staged(box(x,7.02,.98,.5,.12,4.45,mats.dark),.81,.95);a.rotation.x=.55;b.rotation.x=-.55}
const pads=[{x:-7,z:7,c:0x57ff6b,name:'СКЛАД',cost:3200,key:'cargo'},{x:-2.5,z:7,c:0x35bfff,name:'СКОРОСТЬ',cost:3400,key:'speed'},{x:2,z:7,c:0xffd129,name:'ДОХОД',cost:4800,key:'income'},{x:6.5,z:7,c:0xff8d24,name:'ДОСТАВКА',cost:1500,key:'delivery'}];for(const p of pads){p.ring=mesh(new THREE.TorusGeometry(1.25,.09,14,60),new THREE.MeshBasicMaterial({color:p.c}),p.x,.08,p.z);p.ring.rotation.x=Math.PI/2;const d=mesh(new THREE.CircleGeometry(1.12,48),new THREE.MeshBasicMaterial({color:p.c,transparent:true,opacity:.12}),p.x,.03,p.z);d.rotation.x=-Math.PI/2}
const player=new THREE.Group();world.add(player);const body=part(player,new THREE.CapsuleGeometry(.42,1.05,6,12),mats.white,0,1.22,0);part(player,new THREE.SphereGeometry(.29,20,16),M(0xd3a078,.85),0,2.05,0);const legs=[-.18,.18].map(x=>part(player,new THREE.BoxGeometry(.22,.85,.25),mats.dark,x,.46,0));const arms=[-.48,.48].map(x=>part(player,new THREE.BoxGeometry(.18,.85,.2),mats.white,x,1.3,0));const cargo=part(player,new THREE.BoxGeometry(.9,.55,.7),mats.brick,0,1.25,.55);player.position.set(-8,0,-1);
const defaultState={v:41,money:12450,brick:1860,wood:1540,progress:0,speed:1,cargo:1,income:1,auto:true,run:false,dir:1};let state={...defaultState};try{const s=JSON.parse(localStorage.getItem('er_v41')||'null');if(s&&s.v===41)Object.assign(state,s)}catch{}const input={x:0,y:0,active:false,id:null};let autoT=0,last=performance.now(),fps=60,frames=0,fpsAt=performance.now(),loaded=0,failed=0,paused=false;
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('on');clearTimeout(toast.i);toast.i=setTimeout(()=>e.classList.remove('on'),1200)}function updateBuild(){for(const o of build){const q=THREE.MathUtils.clamp((state.progress-o.userData.a)/(o.userData.b-o.userData.a),0,1);grow(o,q)}}
function resetInput(){input.active=false;input.id=null;input.x=input.y=0;$('knob').style.transform='';state.run=false}
function update(dt,t){let moving=false;if(state.auto){autoT+=dt*.16*state.speed*state.dir;if(autoT>=1){autoT=1;state.dir=-1;state.progress=Math.min(1,state.progress+.006*state.cargo);state.money+=8*state.cargo*state.income}if(autoT<=0){autoT=0;state.dir=1}player.position.lerpVectors(new THREE.Vector3(-8,0,-1),new THREE.Vector3(-1,0,-1),autoT);moving=true;cargo.visible=state.dir>0}else if(input.active){const mult=state.run?2:1;player.position.x=THREE.MathUtils.clamp(player.position.x+input.x*dt*4*state.speed*mult,-15,15);player.position.z=THREE.MathUtils.clamp(player.position.z+input.y*dt*4*state.speed*mult,-12,12);if(Math.abs(input.x)+Math.abs(input.y)>.08){player.rotation.y=Math.atan2(input.x,input.y);moving=true}cargo.visible=false}const walk=moving?Math.sin(t*.012*state.speed*(state.run?1.8:1)):0;arms[0].rotation.x=walk*.8;arms[1].rotation.x=-walk*.8;legs[0].rotation.x=-walk*.65;legs[1].rotation.x=walk*.65;player.position.y=Math.abs(walk)*.04;for(const p of pads){p.ring.scale.setScalar(1+Math.sin(t*.004)*.05);const d=Math.hypot(player.position.x-p.x,player.position.z-p.z);p.ring.material.opacity=d<1.7?1:.68;p.ring.material.transparent=true;if(d<1.3&&!state.auto&&!p.lock){p.lock=true;if(state.money>=p.cost){state.money-=p.cost;if(p.key==='delivery')state.progress=Math.min(1,state.progress+.05);else state[p.key]+=p.key==='speed'?.2:1;toast(p.name+' улучшено')}else toast('Не хватает денег')}if(d>1.6)p.lock=false}updateBuild();ex.rotation.y=Math.sin(t*.00035)*.08;boom.rotation.z=-.6+Math.sin(t*.001)*.12;camera.position.lerp(new THREE.Vector3(player.position.x+10,player.position.y+9.5,player.position.z+13),Math.min(1,dt*3.7));camera.lookAt(player.position.x,1.65,player.position.z)}
const loader=new GLTFLoader(),root='https://raw.githubusercontent.com/KenneyNL/Starter-Kit-City-Builder/4535092b740b378b700efd9df9e27a631815b84a/models/',assets=[['building-garage.glb',-13,0,-6,2.6],['building-small-a.glb',14,0,-8,2.8],['grass-trees.glb',-16,0,10,3.2],['grass-trees-tall.glb',14,0,11,3.2],['road-straight-lightposts.glb',0,0,15,3.5]];function loadDone(ok){loaded++;if(!ok)failed++;loadFill.style.width=(10+loaded/assets.length*90)+'%';loadText.textContent=`Ассеты: ${loaded}/${assets.length}`;if(loaded===assets.length)setTimeout(()=>loading.remove(),250)}for(const [file,x,y,z,s] of assets)loader.load(root+file,g=>{g.scene.position.set(x,y,z);g.scene.scale.setScalar(s);g.scene.traverse(o=>{if(o.isMesh){o.castShadow=o.receiveShadow=true;if(o.material?.map)o.material.map.colorSpace=THREE.SRGBColorSpace}});scene.add(g.scene);loadDone(true)},undefined,()=>loadDone(false));setTimeout(()=>{if(loading.isConnected){loadText.textContent='Запуск без части внешних моделей';loading.remove()}},9000);
const joy=$('joy'),knob=$('knob');function setJoy(cx,cy){const r=joy.getBoundingClientRect(),dx=cx-(r.left+r.width/2),dy=cy-(r.top+r.height/2),max=34,l=Math.hypot(dx,dy)||1,k=Math.min(1,max/l);input.x=dx*k/max;input.y=dy*k/max;knob.style.transform=`translate(${dx*k}px,${dy*k}px)`}joy.addEventListener('pointerdown',e=>{e.preventDefault();state.auto=false;$('auto').textContent='АВТО: ВЫКЛ';input.active=true;input.id=e.pointerId;try{joy.setPointerCapture(e.pointerId)}catch{}setJoy(e.clientX,e.clientY)});joy.addEventListener('pointermove',e=>{if(input.active&&e.pointerId===input.id){e.preventDefault();setJoy(e.clientX,e.clientY)}});['pointerup','pointercancel','lostpointercapture'].forEach(n=>joy.addEventListener(n,resetInput));$('auto').onclick=()=>{state.auto=!state.auto;resetInput();$('auto').textContent='АВТО: '+(state.auto?'ВКЛ':'ВЫКЛ')};const run=$('run');run.addEventListener('pointerdown',e=>{e.preventDefault();state.run=true;try{run.setPointerCapture(e.pointerId)}catch{}});['pointerup','pointercancel','lostpointercapture','pointerleave'].forEach(n=>run.addEventListener(n,()=>state.run=false));$('quality').onclick=()=>{quality=quality==='high'?'economy':'high';applyQuality();renderer.setSize(innerWidth,innerHeight,false)};$('diagBtn').onclick=()=>$('diag').classList.toggle('open');$('reset').onclick=()=>{localStorage.removeItem('er_v41');location.reload()};
function ui(){money.textContent=Math.floor(state.money).toLocaleString('ru');brick.textContent=state.brick;wood.textContent=state.wood;const pc=Math.round(state.progress*100);pct.textContent=pc+'%';fill.style.width=pc+'%';stage.textContent=pc<5?'Расчистка':pc<14?'Фундамент':pc<23?'Плита':pc<44?'Стены 1 этажа':pc<52?'Перекрытие':pc<69?'Стены 2 этажа':pc<81?'Стропила':pc<95?'Кровля':'Отделка';$('diagText').textContent=`FPS: ${fps}\nGLB загружено: ${loaded-failed}/${assets.length}\nРежим: ${quality}\nWebGL: работает\nУправление: ${input.active?'активно':'готово'}`}
function loop(t){if(paused){last=t;requestAnimationFrame(loop);return}const dt=Math.min(.033,Math.max(0,(t-last)/1000));last=t;update(dt,t);ui();renderer.render(scene,camera);frames++;if(t-fpsAt>1000){fps=frames;frames=0;fpsAt=t;if(fps<35&&quality==='high'){quality='economy';applyQuality();toast('Включён эконом-режим')}}requestAnimationFrame(loop)}requestAnimationFrame(loop);setInterval(()=>{try{localStorage.setItem('er_v41',JSON.stringify(state))}catch{}},2000);document.addEventListener('visibilitychange',()=>{paused=document.hidden;resetInput();last=performance.now()});addEventListener('blur',resetInput);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});window.addEventListener('error',e=>{console.error(e.error||e.message);$('diagText').textContent+='\nОшибка: '+e.message});