(function(){
'use strict';
var boot=document.getElementById('boot'),bootText=document.getElementById('bootText'),bootDetail=document.getElementById('bootDetail'),bootFill=document.getElementById('bootFill');
var diag={engine:false,baseScene:false,modelSource:false,modelDecoded:false,modelParsed:false,modelNodes:0,modelMeshes:0,modelMode:'ожидание',fps:0,lastError:''};
function setBoot(p,title,detail){bootFill.style.width=p+'%';if(title)bootText.textContent=title;if(detail)bootDetail.textContent=detail}
function fatal(message){diag.lastError=String(message);setBoot(100,'Ошибка запуска сцены',String(message));boot.style.background='#16110f'}
window.addEventListener('error',function(e){diag.lastError=e.message||'Ошибка JavaScript'});
if(!window.THREE){fatal('Локальный Three.js не загрузился');return}
diag.engine=true;setBoot(14,'Создание освещения…','Движок загружен локально');

try{
var canvas=document.getElementById('game');
var renderer=new THREE.WebGLRenderer({canvas:canvas,antialias:true,alpha:false,powerPreference:'high-performance'});
var mobile=Math.min(innerWidth,innerHeight)<800;
var pixelRatio=Math.min(devicePixelRatio||1,mobile?1.25:1.6);
renderer.setPixelRatio(pixelRatio);renderer.setSize(innerWidth,innerHeight,false);
renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
var scene=new THREE.Scene();scene.background=new THREE.Color(0x6d806d);scene.fog=new THREE.FogExp2(0x718070,.0125);
var camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,180);camera.position.set(18,17,22);
var world=new THREE.Group();scene.add(world);
var hemi=new THREE.HemisphereLight(0xdff2e4,0x483424,1.25);scene.add(hemi);
var sun=new THREE.DirectionalLight(0xffd39b,3.35);sun.position.set(-18,28,-12);sun.castShadow=true;sun.shadow.mapSize.width=sun.shadow.mapSize.height=mobile?1024:1536;sun.shadow.camera.left=-31;sun.shadow.camera.right=31;sun.shadow.camera.top=31;sun.shadow.camera.bottom=-31;sun.shadow.camera.near=1;sun.shadow.camera.far=75;sun.shadow.bias=-.00018;scene.add(sun);
var fill=new THREE.DirectionalLight(0x9cc5df,.42);fill.position.set(20,11,18);scene.add(fill);

function material(color,rough,metal,extra){var o={color:color,roughness:rough==null?.82:rough,metalness:metal||0};if(extra)Object.assign(o,extra);return new THREE.MeshStandardMaterial(o)}
var M={grass:material(0x405b37,1),dirt:material(0x6f5139,.98),mud:material(0x503a2c,1),brick:material(0x9b4327,.9),brick2:material(0xb35431,.88),concrete:material(0xa4a19a,.94),wood:material(0x805128,.9),woodLight:material(0xad7440,.86),steel:material(0x343b3a,.58,.58),dark:material(0x1d2322,.65,.45),yellow:material(0xc98214,.62,.16),orange:material(0xd27318,.62,.12),glass:material(0x37545c,.08,.15,{transparent:true,opacity:.48,depthWrite:false}),green:material(0x244d38,.8,.08),white:material(0xd7d4cc,.88),rubber:material(0x151918,.88,.05),chrome:material(0xaeb7b5,.24,.9)};
function box(parent,name,x,y,z,w,h,d,mat,cast){var mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.name=name||'';mesh.position.set(x,y,z);mesh.castShadow=cast!==false;mesh.receiveShadow=true;(parent||world).add(mesh);return mesh}
function cyl(parent,name,x,y,z,r,h,mat,segments){var mesh=new THREE.Mesh(new THREE.CylinderGeometry(r,r,h,segments||14),mat);mesh.name=name||'';mesh.position.set(x,y,z);mesh.castShadow=mesh.receiveShadow=true;(parent||world).add(mesh);return mesh}
function beam(parent,a,b,r,mat,name){var va=new THREE.Vector3(a[0],a[1],a[2]),vb=new THREE.Vector3(b[0],b[1],b[2]),mid=va.clone().add(vb).multiplyScalar(.5),len=va.distanceTo(vb);var o=new THREE.Mesh(new THREE.CylinderGeometry(r,r,len,8),mat);o.name=name||'beam';o.position.copy(mid);o.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),vb.clone().sub(va).normalize());o.castShadow=o.receiveShadow=true;(parent||world).add(o);return o}
function makeDirtTexture(){var c=document.createElement('canvas');c.width=c.height=512;var x=c.getContext('2d');x.fillStyle='#72553c';x.fillRect(0,0,512,512);var im=x.getImageData(0,0,512,512),d=im.data;for(var i=0;i<d.length;i+=4){var n=(Math.random()-.5)*42;d[i]=Math.max(0,d[i]+n);d[i+1]=Math.max(0,d[i+1]+n*.75);d[i+2]=Math.max(0,d[i+2]+n*.48)}x.putImageData(im,0,0);x.globalAlpha=.24;for(var k=0;k<260;k++){x.fillStyle=k%3?'#3c2c22':'#aa8961';var r=Math.random()*3+.4;x.beginPath();x.arc(Math.random()*512,Math.random()*512,r,0,Math.PI*2);x.fill()}x.globalAlpha=.28;x.strokeStyle='#30251f';x.lineWidth=4;for(var t=0;t<7;t++){x.beginPath();x.moveTo(-20,t*80+Math.random()*30);x.bezierCurveTo(130,t*80-20,330,t*80+50,540,t*80);x.stroke()}var tex=new THREE.CanvasTexture(c);tex.wrapS=tex.wrapT=THREE.RepeatWrapping;tex.repeat.set(4.5,4.5);tex.anisotropy=Math.min(8,renderer.capabilities.getMaxAnisotropy());tex.encoding=THREE.sRGBEncoding;return tex}
M.dirt.map=makeDirtTexture();M.dirt.bumpMap=M.dirt.map;M.dirt.bumpScale=.12;M.dirt.needsUpdate=true;
var ground=new THREE.Mesh(new THREE.PlaneGeometry(100,100),M.grass);ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;scene.add(ground);
var site=new THREE.Mesh(new THREE.PlaneGeometry(40,31,1,1),M.dirt);site.rotation.x=-Math.PI/2;site.position.y=.025;site.receiveShadow=true;world.add(site);
for(var road=-22;road<=22;road+=4)box(world,'road',road,.07,17,3.2,.14,3.5,M.dark,false);
for(var fi=-19;fi<=19;fi+=2){box(world,'fenceBack',fi,1.2,-14.6,1.8,2.4,.12,M.steel,false);box(world,'fenceFront',fi,1.2,14.6,1.8,2.4,.12,M.steel,false)}
for(var fz=-13;fz<=13;fz+=2){box(world,'fenceLeft',-19.5,1.2,fz,.12,2.4,1.8,M.steel,false);box(world,'fenceRight',19.5,1.2,fz,.12,2.4,1.8,M.steel,false)}

function makeHouse(){var g=new THREE.Group();g.name='DETAILED_HOUSE';world.add(g);var ox=1,oz=-2;
box(g,'slab',ox,.32,oz,11,.62,8,M.concrete);
var brickGeo=new THREE.BoxGeometry(.62,.3,.34);var rows=13,frontCount=16,sideCount=10,total=rows*(frontCount*2+sideCount*2);var inst=new THREE.InstancedMesh(brickGeo,M.brick,total);inst.castShadow=inst.receiveShadow=true;var dummy=new THREE.Object3D(),idx=0;
for(var r=0;r<rows;r++){var offset=r%2?.31:0;for(var i=0;i<frontCount;i++){var xx=ox-5+i*.67+offset;for(var side=-1;side<=1;side+=2){var skip=(r<7&&((i>4&&i<7)||(i>10&&i<13)));if(skip)continue;dummy.position.set(xx,1+r*.31,oz+side*3.7);dummy.updateMatrix();inst.setMatrixAt(idx++,dummy.matrix)}}for(var j=0;j<sideCount;j++){var zz=oz-3.35+j*.7+offset;for(var sx=-1;sx<=1;sx+=2){var skip2=(r<7&&j>3&&j<7);if(skip2)continue;dummy.position.set(ox+sx*5.35,1+r*.31,zz);dummy.rotation.y=Math.PI/2;dummy.updateMatrix();inst.setMatrixAt(idx++,dummy.matrix);dummy.rotation.y=0}}}
inst.count=idx;g.add(inst);
box(g,'upperSlab',ox,5.05,oz,11.3,.34,8.2,M.concrete);
for(var p=-5;p<=5;p+=1.25)for(var z=-3.6;z<=3.6;z+=7.2)box(g,'upperWall',ox+p,5.85,oz+z,1.08,1.35,.42,(Math.round(p*10)%2)?M.brick:M.brick2);
for(var x=-4.7;x<=4.7;x+=.85){var a=beam(g,[ox+x,6.55,oz],[ox+x,8.65,oz-4.35],.095,M.woodLight,'rafter');var b=beam(g,[ox+x,6.55,oz],[ox+x,8.65,oz+4.35],.095,M.woodLight,'rafter')}
for(var lx=-6;lx<=6;lx+=6)for(var lz=-4.6;lz<=4.6;lz+=1.15){beam(g,[ox+lx,.2,oz+lz],[ox+lx,7,oz+lz],.055,M.steel,'scaffold');beam(g,[ox+lx-1,.8,oz+lz],[ox+lx+1,2.3,oz+lz],.038,M.steel,'brace')}
for(var py=1;py<=7;py+=1.35)for(var lz2=-4.6;lz2<=4.6;lz2+=1.15)beam(g,[ox-6,py,oz+lz2],[ox+6,py,oz+lz2],.045,M.steel,'scaffoldDeck');
return g}
var house=makeHouse();

function palletStack(x,z,type){var g=new THREE.Group();g.position.set(x,0,z);world.add(g);box(g,'pallet',0,.12,0,2,.24,1.35,M.wood);if(type==='brick'){for(var r=0;r<5;r++)for(var i=0;i<8;i++)box(g,'brick',- .78+i*.22,.31+r*.19,0,.2,.16,.45,r%2?M.brick:M.brick2)}else if(type==='block'){for(var rr=0;rr<4;rr++)for(var ii=0;ii<5;ii++)box(g,'block',-.75+ii*.37,.34+rr*.27,0,.34,.23,.55,M.concrete)}else{for(var w=0;w<8;w++)box(g,'board',0,.35+w*.13,0,2.15,.1,.22,w%2?M.wood:M.woodLight)}return g}
[[-13,-8,'block'],[-10,-8,'brick'],[-6,9,'wood'],[8,9,'brick'],[13,7,'block'],[12,-9,'wood'],[-14,8,'brick'],[6,-10,'block']].forEach(function(p){palletStack(p[0],p[1],p[2])});
box(world,'container',-14,1.65,1,5.5,3.3,4,M.green);box(world,'containerRoof',-14,3.36,1,5.8,.16,4.25,M.dark);box(world,'containerDoor',-11.22,1.65,1,.12,2.8,3.4,M.dark);
for(var pipe=0;pipe<8;pipe++){var pp=cyl(world,'pipe',11.5+(pipe%4)*.68,.42+Math.floor(pipe/4)*.68,-11,.3,2.5,M.concrete,20);pp.rotation.z=Math.PI/2}

function makeCrane(){var g=new THREE.Group();g.position.set(13,0,-8);world.add(g);for(var y=0;y<15;y+=1.1){for(var s=-1;s<=1;s+=2)for(var z=-1;z<=1;z+=2)beam(g,[s*.62,y,z*.62],[s*.62,y+1.1,z*.62],.055,M.yellow,'craneMast');beam(g,[-.62,y,-.62],[.62,y+1.1,.62],.035,M.yellow);beam(g,[.62,y,-.62],[-.62,y+1.1,.62],.035,M.yellow)}box(g,'craneCab',-.1,12.9,-.9,1.7,1.8,1.45,M.white);box(g,'craneWindow',-.1,13,-1.63,1.35,1.12,.04,M.glass);for(var x=-2;x<=13;x+=1.15){beam(g,[x,14.4,0],[x+1.15,14.4,0],.055,M.yellow);beam(g,[x,14.4,0],[x+1.15,15.05,0],.04,M.yellow);beam(g,[x,15.05,0],[x+1.15,14.4,0],.04,M.yellow)}beam(g,[-4,14.4,0],[13,14.4,0],.06,M.yellow);beam(g,[-4,15.05,0],[13,15.05,0],.045,M.yellow);beam(g,[7.5,14.4,0],[7.5,8.2,0],.018,M.dark);box(g,'craneLoad',7.5,7.75,0,1.4,.9,1.2,M.concrete);return g}
var crane=makeCrane();

function makeMixerTruck(){var g=new THREE.Group();g.position.set(13,0,1);g.rotation.y=-.55;world.add(g);box(g,'chassis',0,.65,0,5,.62,2,M.dark);box(g,'cab',-1.7,1.55,0,1.65,1.75,1.85,M.orange);box(g,'windshield',-2.54,1.72,0,.05,.8,1.45,M.glass);var drum=new THREE.Mesh(new THREE.CylinderGeometry(.75,1.15,2.8,24),M.white);drum.rotation.z=Math.PI/2;drum.position.set(.7,1.75,0);drum.castShadow=drum.receiveShadow=true;g.add(drum);for(var stripe=-.8;stripe<=.8;stripe+=.55){var ring=new THREE.Mesh(new THREE.TorusGeometry(.96,.08,10,28),M.orange);ring.rotation.y=Math.PI/2;ring.position.set(.7+stripe,1.75,0);g.add(ring)}for(var wx=-1.65;wx<=1.65;wx+=1.65)for(var wz=-1;wz<=1;wz+=2){var wh=cyl(g,'wheel',wx,.38,wz,.45,.28,M.rubber,20);wh.rotation.x=Math.PI/2}return g}
var mixerTruck=makeMixerTruck();

var pads=[{key:'warehouse',x:-8,z:6,c:0x5eff67},{key:'income',x:-2,z:4.2,c:0xffdc35},{key:'speed',x:6,z:5.5,c:0x56cfff},{key:'cargo',x:-5,z:10,c:0xd064ff},{key:'delivery',x:7,z:10,c:0xff8d3d}];
pads.forEach(function(p){var ring=new THREE.Mesh(new THREE.TorusGeometry(1.18,.08,12,48),new THREE.MeshBasicMaterial({color:p.c}));ring.rotation.x=Math.PI/2;ring.position.set(p.x,.09,p.z);ring.userData.pad=p;world.add(ring);p.ring=ring});

function addPart(parent,geo,mat,x,y,z,name){var o=new THREE.Mesh(geo,mat);o.name=name||'';o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;parent.add(o);return o}
function fallbackExcavator(){var g=new THREE.Group();g.name='EXCAVATOR_FALLBACK';for(var side=-1;side<=1;side+=2){box(g,'TRACK_FRAME',0,.48,side*.95,4.4,.8,.55,M.dark);for(var i=-1.65;i<=1.65;i+=.55){var rw=cyl(g,'TRACK_ROLLER',i,.48,side*1.02,.24,.22,M.steel,16);rw.rotation.x=Math.PI/2}for(var t=-2;t<=2;t+=.23)box(g,'TRACK_PAD',t,.13,side*.98,.18,.09,.72,M.rubber)}cyl(g,'SLEW_RING',0,1.05,0,.85,.3,M.steel,28);box(g,'UPPER_PLATFORM',-.2,1.28,0,3.8,.42,2.25,M.yellow);box(g,'ENGINE_HOUSING',.9,2.05,0,2.05,1.45,2,M.yellow);box(g,'CABIN',-.95,2.2,-.02,1.45,1.85,1.75,M.yellow);box(g,'CABIN_GLASS',-1.7,2.3,-.02,.04,1.3,1.4,M.glass);var boom=beam(g,[-1.4,2.45,0],[-4.1,4.55,0],.22,M.yellow,'BOOM');var stick=beam(g,[-4.1,4.55,0],[-5.15,1.35,0],.19,M.yellow,'STICK');beam(g,[-1.5,2.7,-.3],[-3.7,4.25,-.3],.07,M.chrome,'HYDRAULIC');beam(g,[-3.95,4.3,-.3],[-4.95,1.55,-.3],.065,M.chrome,'HYDRAULIC');var bucket=box(g,'BUCKET',-5.3,.85,0,1.1,.85,1.35,M.steel);bucket.rotation.z=-.25;return g}
var excavatorRoot=new THREE.Group();excavatorRoot.name='EXCAVATOR_SLOT';excavatorRoot.position.set(10,0,-5);excavatorRoot.rotation.y=-.25;world.add(excavatorRoot);var currentExcavator=fallbackExcavator();excavatorRoot.add(currentExcavator);

function tuneImported(root){var meshCount=0;root.traverse(function(o){if(!o.isMesh)return;meshCount++;o.castShadow=o.receiveShadow=true;var n=((o.name||'')+' '+(o.material&&o.material.name||'')).toUpperCase();if(n.indexOf('GLASS')>=0||n.indexOf('WINDOW')>=0)o.material=M.glass;else if(n.indexOf('TRACK')>=0||n.indexOf('TREAD')>=0||n.indexOf('RUBBER')>=0)o.material=M.rubber;else if(n.indexOf('HYDRAULIC')>=0||n.indexOf('ROD')>=0||n.indexOf('CHROME')>=0)o.material=M.chrome;else if(n.indexOf('BUCKET')>=0||n.indexOf('TOOTH')>=0)o.material=material(0x5b5146,.66,.72);else if(n.indexOf('CABIN')>=0||n.indexOf('BOOM')>=0||n.indexOf('STICK')>=0||n.indexOf('YELLOW')>=0||n.indexOf('BODY')>=0)o.material=material(0xd08b19,.58,.22);else if(o.material){o.material.roughness=Math.min(.9,o.material.roughness==null?.8:o.material.roughness);o.material.metalness=Math.max(.08,o.material.metalness||0);o.material.needsUpdate=true}});diag.modelMeshes=meshCount}
function accessorArray(json,bin,index){var a=json.accessors[index],bv=json.bufferViews[a.bufferView],components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT2:4,MAT3:9,MAT4:16}[a.type],Ctor={5120:Int8Array,5121:Uint8Array,5122:Int16Array,5123:Uint16Array,5125:Uint32Array,5126:Float32Array}[a.componentType];if(!Ctor)throw new Error('Неизвестный componentType '+a.componentType);var bytes=Ctor.BYTES_PER_ELEMENT,packed=components*bytes,stride=bv.byteStride||packed,offset=(bv.byteOffset||0)+(a.byteOffset||0),count=a.count;if(stride===packed&&offset%bytes===0)return{array:new Ctor(bin,offset,count*components),itemSize:components,normalized:!!a.normalized};var out=new Ctor(count*components),view=new DataView(bin);for(var i=0;i<count;i++)for(var c=0;c<components;c++){var pos=offset+i*stride+c*bytes;var value;if(a.componentType===5126)value=view.getFloat32(pos,true);else if(a.componentType===5125)value=view.getUint32(pos,true);else if(a.componentType===5123)value=view.getUint16(pos,true);else if(a.componentType===5122)value=view.getInt16(pos,true);else if(a.componentType===5121)value=view.getUint8(pos);else value=view.getInt8(pos);out[i*components+c]=value}return{array:out,itemSize:components,normalized:!!a.normalized}}
function parseGLB(arrayBuffer){var dv=new DataView(arrayBuffer);if(dv.getUint32(0,true)!==0x46546c67)throw new Error('Файл не является GLB');var length=dv.getUint32(8,true),off=12,json=null,bin=null;while(off<length){var size=dv.getUint32(off,true),type=dv.getUint32(off+4,true),data=arrayBuffer.slice(off+8,off+8+size);if(type===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(data));else if(type===0x004e4942)bin=data;off+=8+size}if(!json||!bin)throw new Error('В GLB нет JSON или BIN секции');var mats=(json.materials||[]).map(function(m){var p=m.pbrMetallicRoughness||{},factor=p.baseColorFactor||[.8,.8,.8,1],mt=new THREE.MeshStandardMaterial({color:new THREE.Color(factor[0],factor[1],factor[2]),opacity:factor[3],transparent:factor[3]<1,roughness:p.roughnessFactor==null?1:p.roughnessFactor,metalness:p.metallicFactor||0,side:m.doubleSided?THREE.DoubleSide:THREE.FrontSide});mt.name=m.name||'';return mt});
function meshInstance(meshIndex){var def=json.meshes[meshIndex],group=new THREE.Group();group.name=def.name||('mesh_'+meshIndex);def.primitives.forEach(function(pr){var geo=new THREE.BufferGeometry();Object.keys(pr.attributes||{}).forEach(function(key){var a=accessorArray(json,bin,pr.attributes[key]),attr=new THREE.BufferAttribute(a.array,a.itemSize,a.normalized),name={POSITION:'position',NORMAL:'normal',TEXCOORD_0:'uv',COLOR_0:'color',TANGENT:'tangent'}[key];if(name)geo.setAttribute(name,attr)});if(pr.indices!=null){var ix=accessorArray(json,bin,pr.indices);geo.setIndex(new THREE.BufferAttribute(ix.array,1))}if(!geo.attributes.normal)geo.computeVertexNormals();geo.computeBoundingBox();var mt=mats[pr.material]||M.yellow,me=new THREE.Mesh(geo,mt);me.castShadow=me.receiveShadow=true;group.add(me)});return group}
var objects=(json.nodes||[]).map(function(n,i){var o=n.mesh!=null?meshInstance(n.mesh):new THREE.Group();o.name=n.name||('node_'+i);if(n.matrix){var matrix=new THREE.Matrix4();matrix.fromArray(n.matrix);o.applyMatrix4(matrix)}else{if(n.translation)o.position.fromArray(n.translation);if(n.rotation)o.quaternion.fromArray(n.rotation);if(n.scale)o.scale.fromArray(n.scale)}return o});(json.nodes||[]).forEach(function(n,i){(n.children||[]).forEach(function(ch){objects[i].add(objects[ch])})});var root=new THREE.Group(),sceneDef=(json.scenes||[])[json.scene||0]||{nodes:[0]};(sceneDef.nodes||[]).forEach(function(i){root.add(objects[i])});diag.modelNodes=objects.length;return root}
function b64Bytes(text){var clean=text.replace(/\s+/g,''),raw=atob(clean),out=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function gunzip(bytes){if(bytes[0]!==31||bytes[1]!==139)return bytes.buffer;if(typeof DecompressionStream==='undefined')throw new Error('Safari не поддерживает распаковку gzip');var stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return await new Response(stream).arrayBuffer()}
async function loadActualExcavator(){try{setBoot(56,'Загрузка реального экскаватора…','Чтение встроенного GLB');var response=await fetch('source/model.part-00?v=5001',{cache:'no-store'});if(!response.ok)throw new Error('model.part-00: HTTP '+response.status);diag.modelSource=true;var text=await response.text();var compressed=b64Bytes(text);setBoot(68,'Распаковка модели…',Math.round(compressed.byteLength/1024)+' КБ');var glb=await gunzip(compressed);diag.modelDecoded=true;setBoot(79,'Сборка GLB-узлов…',Math.round(glb.byteLength/1024)+' КБ после распаковки');var imported=parseGLB(glb);diag.modelParsed=true;tuneImported(imported);imported.rotation.x=-Math.PI/2;imported.updateMatrixWorld(true);var bb=new THREE.Box3().setFromObject(imported),size=new THREE.Vector3(),center=new THREE.Vector3();bb.getSize(size);bb.getCenter(center);var scale=7.4/Math.max(size.x,size.z,size.y*1.25);imported.scale.multiplyScalar(scale);imported.updateMatrixWorld(true);bb.setFromObject(imported);bb.getCenter(center);imported.position.x-=center.x;imported.position.z-=center.z;imported.position.y-=bb.min.y;excavatorRoot.remove(currentExcavator);currentExcavator=imported;excavatorRoot.add(imported);diag.modelMode='реальный GLB';document.getElementById('diagnostics').textContent='3D: GLB ✓';setBoot(96,'Финальная настройка…','Экскаватор встроен: '+diag.modelMeshes+' мешей');return true}catch(err){diag.lastError=err&&err.message?err.message:String(err);diag.modelMode='резервная модель';document.getElementById('diagnostics').textContent='3D: РЕЗЕРВ';setBoot(92,'Сцена готова','Резервный экскаватор: '+diag.lastError);return false}}

var player=new THREE.Group();player.name='PLAYER';world.add(player);var torso=addPart(player,new THREE.CylinderGeometry(.42,.48,1.25,12),M.white,0,1.35,0,'torso');var head=addPart(player,new THREE.SphereGeometry(.28,16,12),material(0xc58f6b,.85),0,2.12,0,'head');var cap=addPart(player,new THREE.CylinderGeometry(.3,.3,.12,14),M.dark,0,2.38,0,'cap');var arms=[],legs=[];[-.53,.53].forEach(function(x){arms.push(addPart(player,new THREE.BoxGeometry(.18,.85,.2),M.white,x,1.4,0,'arm'))});[-.2,.2].forEach(function(x){legs.push(addPart(player,new THREE.BoxGeometry(.23,.92,.28),M.dark,x,.49,0,'leg'))});var cargo=addPart(player,new THREE.BoxGeometry(.95,.58,.72),M.brick,0,1.35,.55,'cargo');cargo.visible=false;player.position.set(-9,0,8);

var state={version:5,money:12450,sand:2450,brick:1860,cement:980,wood:1540,progress:.35,level:12,xp:2350,xpMax:3500,auto:true,run:false,carrying:false,cargoCount:0,cargoMax:20,speed:1,levels:{warehouse:5,income:7,speed:6,cargo:4,delivery:3},costs:{warehouse:3200,income:4800,speed:3400,cargo:2100,delivery:1500}};
try{var saved=JSON.parse(localStorage.getItem('er_v5')||'null');if(saved&&saved.version===5)Object.assign(state,saved)}catch(e){}
var input={active:false,id:null,x:0,y:0},autoPoints=[new THREE.Vector3(-9,0,8),new THREE.Vector3(-13,0,1),new THREE.Vector3(-9,0,8),new THREE.Vector3(-1,0,1),new THREE.Vector3(-9,0,8)],autoIndex=0,last=performance.now(),fpsFrames=0,fpsTime=performance.now(),paused=false;
function toast(html){var e=document.getElementById('toast');e.innerHTML=html;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(function(){e.classList.remove('show')},1500)}
function updateUI(){function n(v){return Math.floor(v).toLocaleString('ru-RU')}document.getElementById('money').textContent='$ '+n(state.money);document.getElementById('sand').textContent=n(state.sand);document.getElementById('brick').textContent=n(state.brick);document.getElementById('cement').textContent=n(state.cement);document.getElementById('wood').textContent=n(state.wood);document.getElementById('level').textContent=state.level;document.getElementById('xp').style.width=Math.min(100,state.xp/state.xpMax*100)+'%';document.getElementById('xpText').textContent=n(state.xp)+' / '+n(state.xpMax)+' XP';var pc=Math.round(state.progress*100);document.getElementById('progressFill').style.width=pc+'%';document.getElementById('progressText').textContent=pc+'%';document.getElementById('stage').textContent=pc<25?'Залейте фундамент':pc<50?'Постройте стены 1 этажа':pc<72?'Постройте стены 2 этажа':pc<92?'Соберите стропильную систему':'Завершите кровлю';Object.keys(state.levels).forEach(function(k){document.getElementById(k+'Level').textContent=state.levels[k];document.getElementById(k+'Cost').textContent=n(state.costs[k])});var panel=document.getElementById('cargoPanel');panel.classList.toggle('show',state.carrying);document.getElementById('cargoFill').style.width=(state.cargoCount/state.cargoMax*100)+'%';document.getElementById('cargoText').textContent=state.cargoCount+'/'+state.cargoMax;document.getElementById('auto').textContent='АВТО: '+(state.auto?'ВКЛ':'ВЫКЛ')}
function nearby(){var wh=Math.hypot(player.position.x+13,player.position.z-1),siteD=Math.hypot(player.position.x+1,player.position.z-1);return wh<2.2?'warehouse':siteD<2.3?'delivery':null}
function interact(){var zone=nearby();if(zone==='warehouse'&&!state.carrying){state.carrying=true;state.cargoCount=state.cargoMax;cargo.visible=true;toast('Загружено: кирпичи ×'+state.cargoMax)}else if(zone==='delivery'&&state.carrying){var reward=state.cargoCount*(10+state.levels.delivery*3);state.money+=reward;state.progress=Math.min(1,state.progress+state.cargoCount*.0035);state.brick=Math.max(0,state.brick-state.cargoCount);state.xp+=35;state.carrying=false;state.cargoCount=0;cargo.visible=false;toast('Доставлено<br><b>+'+Math.floor(reward).toLocaleString('ru-RU')+' ₽</b>')}}
function movePlayer(dt,t){var moving=false,dx=0,dz=0;if(state.auto){var target=autoPoints[autoIndex],v=target.clone().sub(player.position);v.y=0;if(v.length()<.45){if(autoIndex===1&&!state.carrying){state.carrying=true;state.cargoCount=state.cargoMax;cargo.visible=true}if(autoIndex===3&&state.carrying){interact()}autoIndex=(autoIndex+1)%autoPoints.length}else{v.normalize();dx=v.x;dz=v.z;moving=true}}else if(input.active){dx=input.x;dz=input.y;moving=Math.abs(dx)+Math.abs(dz)>.08}if(moving){var mult=(state.run?1.85:1)*(1+(state.levels.speed-1)*.06);player.position.x+=dx*dt*4.2*mult;player.position.z+=dz*dt*4.2*mult;player.position.x=THREE.MathUtils.clamp(player.position.x,-17,17);player.position.z=THREE.MathUtils.clamp(player.position.z,-12.5,12.5);player.rotation.y=Math.atan2(dx,dz)}var walk=moving?Math.sin(t*.012*(state.run?1.65:1)):0;arms[0].rotation.x=walk*.8;arms[1].rotation.x=-walk*.8;legs[0].rotation.x=-walk*.68;legs[1].rotation.x=walk*.68;player.position.y=Math.abs(walk)*.035;var z=nearby();document.getElementById('runIcon').textContent=z?'✋':'🏃';document.getElementById('runText').textContent=z?(z==='warehouse'?'ВЗЯТЬ':'ПОЛОЖИТЬ'):'БЕГ'}
function update(dt,t){movePlayer(dt,t);pads.forEach(function(p){p.ring.scale.setScalar(1+Math.sin(t*.004+p.x)*.045)});mixerTruck.rotation.y=-.55+Math.sin(t*.00025)*.025;crane.children.forEach(function(o){if(o.name==='craneLoad')o.position.y=7.75+Math.sin(t*.001)*.25});state.money+=dt*(115+state.levels.income*7);var camDistance=innerWidth<innerHeight?23:19;var desired=new THREE.Vector3(player.position.x+camDistance*.72,camDistance*.72,player.position.z+camDistance);camera.position.lerp(desired,Math.min(1,dt*2.8));camera.lookAt(player.position.x,2.7,player.position.z-1.5)}

var joy=document.getElementById('joystick'),knob=document.getElementById('knob');function setJoy(x,y){var r=joy.getBoundingClientRect(),dx=x-(r.left+r.width/2),dy=y-(r.top+r.height/2),max=r.width*.3,len=Math.hypot(dx,dy)||1,k=Math.min(1,max/len);dx*=k;dy*=k;input.x=dx/max;input.y=dy/max;knob.style.transform='translate('+dx+'px,'+dy+'px)'}function resetInput(){input.active=false;input.id=null;input.x=input.y=0;state.run=false;knob.style.transform=''}joy.addEventListener('pointerdown',function(e){e.preventDefault();state.auto=false;input.active=true;input.id=e.pointerId;joy.setPointerCapture&&joy.setPointerCapture(e.pointerId);setJoy(e.clientX,e.clientY)});joy.addEventListener('pointermove',function(e){if(input.active&&e.pointerId===input.id){e.preventDefault();setJoy(e.clientX,e.clientY)}});joy.addEventListener('pointerup',resetInput);joy.addEventListener('pointercancel',resetInput);document.getElementById('auto').onclick=function(){state.auto=!state.auto;resetInput();updateUI()};var run=document.getElementById('run');run.addEventListener('pointerdown',function(e){e.preventDefault();if(nearby()){interact();return}state.run=true;run.setPointerCapture&&run.setPointerCapture(e.pointerId)});['pointerup','pointercancel','pointerleave'].forEach(function(ev){run.addEventListener(ev,function(){state.run=false})});document.querySelectorAll('.pad').forEach(function(btn){btn.addEventListener('click',function(){var key=btn.dataset.key,cost=state.costs[key];if(state.money<cost){toast('Не хватает денег');return}state.money-=cost;state.levels[key]++;state.costs[key]=Math.round(cost*1.38);if(key==='cargo')state.cargoMax+=5;if(key==='delivery')state.progress=Math.min(1,state.progress+.025);toast(btn.querySelector('span').textContent+' — уровень '+state.levels[key]);updateUI()})});
var modal=document.getElementById('modal');document.getElementById('diagnostics').onclick=function(){document.getElementById('diagnosticText').textContent='Движок: '+(diag.engine?'OK':'ошибка')+'\nБазовая сцена: '+(diag.baseScene?'OK':'ошибка')+'\nЭкскаватор: '+diag.modelMode+'\nИсточник модели: '+(diag.modelSource?'прочитан':'нет')+'\nРаспаковка: '+(diag.modelDecoded?'OK':'нет')+'\nПарсер GLB: '+(diag.modelParsed?'OK':'нет')+'\nУзлы: '+diag.modelNodes+'\nМеши: '+diag.modelMeshes+'\nFPS: '+diag.fps+'\nPixel ratio: '+pixelRatio+'\nПоследняя ошибка: '+(diag.lastError||'нет');modal.classList.remove('hidden')};document.getElementById('modalClose').onclick=function(){modal.classList.add('hidden')};
document.addEventListener('visibilitychange',function(){paused=document.hidden;last=performance.now();resetInput()});window.addEventListener('blur',resetInput);window.addEventListener('resize',function(){camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false)});
function loop(t){requestAnimationFrame(loop);if(paused)return;var dt=Math.min(.033,Math.max(0,(t-last)/1000));last=t;update(dt,t);updateUI();renderer.render(scene,camera);fpsFrames++;if(t-fpsTime>1000){diag.fps=Math.round(fpsFrames*1000/(t-fpsTime));fpsFrames=0;fpsTime=t}}
diag.baseScene=true;setBoot(42,'Площадка готова','Запуск первого кадра');updateUI();requestAnimationFrame(loop);renderer.render(scene,camera);
loadActualExcavator().finally(function(){setTimeout(function(){boot.style.opacity='0';boot.style.transition='opacity .35s';setTimeout(function(){boot.remove()},380)},450)});
setInterval(function(){try{localStorage.setItem('er_v5',JSON.stringify(state))}catch(e){}},2500);
}catch(err){fatal(err&&err.message?err.message:String(err))}
})();